### ISSUE TITLE
Do you have a script to pull new data?

### ISSUE THREAD

**Issue by mkondel** [pepelepew25/SupDem#1]
This works! I just installed all the python libs, ta-lib, and I see the chart pop up. Just wondering, do you happen to have a ready script that pulls fresh data from GDAX?

**Comment by pepelepew25** [comment]
Yes I will add it.
This program was just a test for now and probably full of bugs still, I did not think someone would use it.

**Comment by mkondel** [comment]
I was looking for any ready made code for the supdem indicator in something other than MT4 (or MT5). I plan to look through your code to see the logic for deciding when a zone starts/ends. This is much appreciated, thanks!
